namespace AppDiv.CRVS.Domain.Enums;
public enum Page{
   Dashboard,
   InProgress,
   Birht,
   Death,
   Marriage,
   Devorce,
   Adoption,
   Certificate,
   Approval,
   Payment,
   UpdateRequest,
   Plan,
   Report,
   Group,
   User,
   YourTeam,
   DocumentSharing,
   Chatting,
   News,
   CertificateTemplateSetting,
   WorkFlowSetting,
   ConfigurationSetting,
   AdministrativeAreaSetting,
   PaymentRateSetting,
   Integration,
   ExemptionRequest,
   AddressLookup,
   EthnicOriginLookup,
   ReligionLookup,
   OwnershipLookup,
   LivingModeLookup,
   BirthTypeLookup,
   FormOfMarriageLookup,
   PhoneTypeLookup,
   RelationshipLookup,
   PersonTitleLookup,
   CategoryLookup,
   InformantTypeLookup,
   OrganizationTypeLookup,
   FacilityTypeLookup,
   EducationStatusLookup,
   TypeOfWorkLookup,
   NationalityLookup




}